"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
import warnings
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# To keep secret keys in environment variables
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Root of the whole repository (one level above the Django project), used to
# locate the ml/ directory that stores notebooks and trained model artifacts.
REPO_ROOT = BASE_DIR.parent

# Make the repo-root-level ml/ package importable as `ml.src...` from
# anywhere in the Django app (and from its tests), since ml/ lives outside
# the Django project directory.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# Directory holding trained model artifacts (e.g. upi_fraud_model.pkl).
# `or` (not getenv's default arg) so an empty string in .env — e.g. a user
# copying .env.example's blank MODEL_ARTIFACT_DIR= verbatim — falls back to
# the default too, not just a fully-unset variable.
MODEL_ARTIFACT_DIR = Path(os.getenv('MODEL_ARTIFACT_DIR') or str(REPO_ROOT / 'ml' / 'artifacts' / 'models'))

# Phase 4: the FastAPI scoring service Django now calls over HTTP instead of
# loading a model in-process. `uvicorn service.main:app --port 8001` from the
# repo root serves this locally by default.
RISK_API_URL = os.getenv('RISK_API_URL') or 'http://localhost:8001'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-dev-only-key-do-not-use-in-production'
        warnings.warn(
            'SECRET_KEY is not set; using an insecure development-only default. '
            'Set SECRET_KEY in your .env before deploying.'
        )
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable must be set when DEBUG=False.')

ALLOWED_HOSTS = [host for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host]

# Render deploy target (2026-08-17): Render injects RENDER_EXTERNAL_HOSTNAME
# automatically (the actual assigned <service>.onrender.com hostname) --
# adding it here means the exact subdomain never has to be known/guessed
# before the first deploy. ".onrender.com" (leading dot -- Django's own
# wildcard-subdomain syntax for ALLOWED_HOSTS) is added too as a fallback,
# harmless on every other deploy target since it's simply never matched
# when the request doesn't come from that domain.
_render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if _render_hostname:
    ALLOWED_HOSTS.append(_render_hostname)
if '.onrender.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.onrender.com')

# CSRF_TRUSTED_ORIGINS needs a full scheme+host (unlike ALLOWED_HOSTS) --
# Django 4.0+ supports a leading-wildcard host here too. Same reasoning as
# ALLOWED_HOSTS above: harmless on every deploy target other than Render.
CSRF_TRUSTED_ORIGINS = [origin for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin]
if _render_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_render_hostname}')
CSRF_TRUSTED_ORIGINS.append('https://*.onrender.com')

if not DEBUG:
    # Security hardening that only makes sense once DEBUG is off (these would
    # break local http:// development, so they're not applied unconditionally).
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Render terminates TLS at its own edge proxy and forwards plain HTTP to
    # the container with this header set -- without it, Django (seeing an
    # apparently-plain-HTTP request) would redirect-loop against
    # SECURE_SSL_REDIRECT above, since it can't otherwise tell the original
    # request arrived over HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UserConfig',
    'social_django',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Phase 5: DATABASE_URL (set by docker-compose.yml, pointing at the `postgres`
# service) switches this to Postgres. Falls back to the pre-existing SQLite
# file when unset, so `manage.py test`/local dev without Docker are unaffected.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = (os.path.join(BASE_DIR, 'static'))
# Django 4.1's setting name (the STORAGES dict API only exists from 4.2+).
# Compression only, not the manifest variant: the vendored bootstrap.min.css
# references a bootstrap.min.css.map that isn't in this repo, which makes
# ManifestStaticFilesStorage's strict reference-checking fail collectstatic.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'


# social auth configs for github
SOCIAL_AUTH_GITHUB_KEY = str(os.getenv('GITHUB_KEY'))
SOCIAL_AUTH_GITHUB_SECRET = str(os.getenv('GITHUB_SECRET'))

# social auth configs for google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = str(os.getenv('GOOGLE_KEY'))
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = str(os.getenv('GOOGLE_SECRET'))

# email configs
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = str(os.getenv('EMAIL_USER'))
EMAIL_HOST_PASSWORD = str(os.getenv('EMAIL_PASSWORD'))

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
