# Generated by Django 4.2.14 on 2024-09-23 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPredictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AverageAmountTransactionDay', models.FloatField()),
                ('TransactionAmount', models.FloatField()),
                ('Is_declined', models.CharField(max_length=100)),
                ('TotalNumberOfDeclinesDay', models.IntegerField()),
                ('isForeignTransaction', models.CharField(max_length=100)),
                ('isHighRiskCountry', models.CharField(max_length=100)),
                ('DailyChargebackAvgAmt', models.FloatField()),
                ('Six_MonthAvgChbkAmt', models.FloatField()),
                ('Six_MonthChbkFreq', models.IntegerField()),
                ('isFradulent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
