# Generated by Django 4.1.2 on 2026-08-12 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpredictmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='fraud_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
