# Generated by Django 4.1.2 on 2026-08-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpredictmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpredictmodel',
            name='action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='event_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='model_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='payee_vpa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='payer_vpa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='reason_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpredictmodel',
            name='risk_tier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='AverageAmountTransactionDay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='DailyChargebackAvgAmt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='Is_declined',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='Six_MonthAvgChbkAmt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='Six_MonthChbkFreq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='TotalNumberOfDeclinesDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='TransactionAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='isForeignTransaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='isFradulent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpredictmodel',
            name='isHighRiskCountry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
