# Generated by Django 5.2.17 on 2026-08-16 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpredictmodel_action_userpredictmodel_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.TextField(unique=True)),
                ('event', models.JSONField()),
                ('feature_snapshot', models.JSONField()),
                ('risk_score', models.FloatField()),
                ('raw_score', models.FloatField()),
                ('is_cold', models.BooleanField()),
                ('action', models.CharField(max_length=20)),
                ('risk_tier', models.CharField(max_length=20)),
                ('reason_codes', models.JSONField()),
                ('model_version', models.CharField(max_length=100)),
                ('thresholds_version', models.CharField(max_length=100)),
                ('feature_lib_version', models.CharField(max_length=100)),
                ('latency_ms', models.FloatField()),
                ('scored_at', models.DateTimeField()),
                ('source', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-scored_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(choices=[('CONFIRMED_FRAUD', 'Confirmed fraud'), ('LEGIT', 'Legitimate'), ('UNCLEAR', 'Unclear')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('decision', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='review_labels', to='users.decision')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
